crawlers:
  - name: javbus
    class: japanese_media_manager.utilities.metadata.JavBusCrawler
  - name: javbooks
    class: japanese_media_manager.utilities.metadata.JavBooksCrawler
route:
  - pattern: "[a-zA-Z]{2,5}-\\d{3,5}"
    metadatas: [JavBusMetaData, AirAVMetaData]
  - pattern: ".+"
    metadatas: [javbus, aData, AvsoxMetaData]
proxies:
    http: None
    https: None
suffixes: [.mp4, .mkv, .wmv]
translator:
    app_id: None
    app_key: None
