crawlers:
  - name: javbus
    class: japanese_media_manager.crawlers.JavBusCrawler
  - name: javbooks
    class: japanese_media_manager.crawlers.JavBooksCrawler
  - name: javdb
    class: japanese_media_manager.crawlers.JavdbCrawler
routing_rules:
  - pattern: ".*"
    crawlers: [javbus, javbooks, javdb]
proxies:
    http: None
    https: None
suffixes: [.mp4, .mkv, .wmv]
translator:
    app_id: None
    app_key: None
